name: Deploy DEV (dev.kpwa.co.uk)

on:
  push:
    branches: [dev]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DEV_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      # Upload everything with default cache
      - name: Sync site to S3 (everything except index.html)
        run: |
          aws s3 sync dist "s3://${{ secrets.S3_BUCKET_DEV }}" --delete --exclude "index.html"
      
      - name: Cache static assetss for 1 year (Vite /assets)
        run: |
          aws s3 sync "dist/assets" "s3://${{ secrets.S3_BUCKET_DEV }}/assets" \
            --delete \
            --cache-control "public,max-age=31536000,immutable"

      # Ensure index.html is not cached aggressively (so releases show up quickly)
      - name: Set cache-control for index.html
        run: |
          aws s3 cp "dist/index.html" "s3://${{ secrets.S3_BUCKET_DEV }}/index.html" \
            --cache-control "no-cache, no-store, must-revalidate" \
            --content-type "text/html" \
            --metadata-directive "REPLACE"

      - name: CloudFront Invalidation (index only)
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${{ secrets.CLOUDFRONT_DIST_ID_DEV }}" \
            --paths "/index.html"
